version: '2'

services:
  nginx:
    image: enclaive/nginx-sgx:latest
    container_name: "nginx-sgx"
    build:
      context: .
    volumes:
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
    ports:
      - '80:80'
      - '443:443'
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
