version: '2'

services:
  nginx:
    image: enclaive/nginx-sgx:latest
    container_name: "nginx-sgx"
    build: .
#    volumes:
#      - "./debug/:/debug/"
    ports:
      - '80:80'
      - '443:443'
    devices:
      - "/dev/sgx/enclave:/dev/sgx/enclave"
      - "/dev/sgx/enclave:/dev/sgx_enclave"
      - "/dev/sgx_provision:/dev/sgx_provision"
